name: xr_tech_tools
description: "XR Tech Tools - Boîte à outils professionnelle pour techniciens informatique"
publish_to: 'none'

version: 1.3.1+20251021

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
  msix: ^3.16.12

flutter:
  uses-material-design: true

  assets:
    - assets/images/app-icon.png
    - assets/images/xrtechtools-bg1.png
    - assets/images/xrtechtools-bg2.png
    - assets/images/xrtechtools-bg3.png
    - assets/images/xrtechtools-bg4.png
    - assets/images/logigrammes/

# Configuration des icônes multi-plateformes
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app-icon.png"
  remove_alpha_ios: false

# ===============================================
# Configuration MSIX pour Windows 10/11
# ===============================================
msix_config:
  # Informations de base
  display_name: XR Tech Tools
  publisher_display_name: Xavier Redondo
  identity_name: com.xrtech.tools
  msix_version: 1.3.1.0
  
  # Icônes et visuels
  logo_path: assets/images/app-icon.png
  
  # Capacités nécessaires (permissions)
  capabilities: internetClient
  
  # Langues supportées
  languages: fr-FR, en-US
  
  # Description pour le Microsoft Store (optionnel)
  description: Application d'entraînement et de pratique professionnelle pour techniciens informatique. Scénarios de dépannage, outils de conversion, et ressources techniques pour les certifications IDI, ADRN et TIP.
  
  # Informations de publication (à personnaliser)
  publisher: CN=Xavier Redondo
  
  # Architecture cible
  architecture: x64
  
  # Protocole personnalisé (si besoin)
  # protocol_activation: xrtech
  
  # Fichiers à inclure/exclure
  # trim_logo: false
  # icons_background_color: transparent
  
  # Certificat de signature (à décommenter quand vous aurez le certificat)
  # certificate_path: C:\path\to\certificate.pfx
  # certificate_password: YOUR_PASSWORD
  
  # Installation système ou utilisateur
  install_certificate: false